# Generated by Django 4.2.1 on 2023-05-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('alias', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
